openapi: 3.0.0
info:
  title: GeoGames API
  version: 1.0.0
servers:
  - url: https://ezhiloli.github.io/geogames-swagger
paths:
  /contryinfo.json:
    get:
      summary: Get country information
      responses:
        '200':
          description: Successful response
